const wordList = [
    {"word": "computer", "hint": "An electronic device used for storing and processing data."},
    {"word": "bicycle", "hint": "A two-wheeled vehicle that you pedal to move."},
    {"word": "library", "hint": "A place where books and other resources are available for reading or borrowing."},
    {"word": "refrigerator", "hint": "An appliance used to keep food and drinks cold."},
    {"word": "microscope", "hint": "A device used to view very small objects by magnifying them."},
    {"word": "telephone", "hint": "A device used for voice communication over distances."},
    {"word": "telescope", "hint": "An instrument used to observe distant objects, typically in the sky."},
    {"word": "dictionary", "hint": "A reference book containing words and their meanings."},
    {"word": "calendar", "hint": "A system for organizing days and months in a year."},
    {"word": "photograph", "hint": "An image captured using a camera."},
    {"word": "airplane", "hint": "A powered flying vehicle with fixed wings."},
    {"word": "television", "hint": "An electronic device for viewing broadcast or recorded video content."},
    {"word": "smartphone", "hint": "A mobile phone with advanced features and computing capability."},
    {"word": "satellite", "hint": "An artificial body placed in orbit around the earth or another planet."},
    {"word": "printer", "hint": "A device that transfers text or graphics from a computer to paper."},
    {"word": "umbrella", "hint": "A portable device used to protect from rain or sunlight."},
    {"word": "calculator", "hint": "A small electronic device used for performing mathematical calculations."},
    {"word": "radio", "hint": "A device for receiving and broadcasting sound waves."},
    {"word": "newspaper", "hint": "A printed publication containing news, articles, and advertisements."},
    {"word": "elevator", "hint": "A platform or compartment housed in a shaft for raising and lowering people or things to different floors or levels."},
    {"word": "headphones", "hint": "A pair of speakers worn over or in the ears for listening to audio."},
    {"word": "skateboard", "hint": "A short board with wheels used for riding on."},
    {"word": "blender", "hint": "An electric device used to mix or puree foods and liquids."},
    {"word": "vacuum", "hint": "A device that uses suction to clean floors and other surfaces."},
    {"word": "toaster", "hint": "An appliance used for toasting bread."},
    {"word": "microwave", "hint": "An appliance that cooks food using microwave radiation."},
    {"word": "stapler", "hint": "A device used for fastening papers together with a staple."},
    {"word": "flashlight", "hint": "A portable hand-held electric light."},
    {"word": "backpack", "hint": "A bag carried on the back, often used by students."},
    {"word": "sunglasses", "hint": "Glasses that protect the eyes from sunlight."},
    {"word": "basketball", "hint": "A large, round ball used in the sport of basketball."},
    {"word": "guitar", "hint": "A stringed musical instrument played by plucking or strumming."},
    {"word": "piano", "hint": "A large keyboard musical instrument with strings that are struck by hammers."},
    {"word": "clock", "hint": "A device used to measure and indicate time."},
    {"word": "lamp", "hint": "A device that produces light."},
    {"word": "bookshelf", "hint": "A piece of furniture with shelves for storing books."},
    {"word": "stove", "hint": "An appliance used for cooking food."},
    {"word": "washing machine", "hint": "A machine used for washing clothes."},
    {"word": "dryer", "hint": "An appliance used to dry clothes after they have been washed."},
    {"word": "oven", "hint": "A chamber used for baking, roasting, or heating food."},
    {"word": "suitcase", "hint": "A case used for carrying clothes and personal items when traveling."},
    {"word": "mirror", "hint": "A reflective surface, typically made of glass, that reflects a clear image."},
    {"word": "notebook", "hint": "A book of blank pages for writing notes."},
    {"word": "camera", "hint": "A device used for capturing video and images."},
    {"word": "pen", "hint": "A writing instrument that uses ink."},
    {"word": "book", "hint": "A written or printed work consisting of pages glued or sewn together along one side."},
    {"word": "chair", "hint": "A piece of furniture for sitting on."},
    {"word": "table", "hint": "A piece of furniture with a flat top and one or more legs."},
    {"word": "curtain", "hint": "A piece of cloth or other material that hangs in a window or other opening."},
    {"word": "toothbrush", "hint": "A small brush used for cleaning teeth."},
    {"word": "toothpaste", "hint": "A paste used with a toothbrush to clean teeth."},
    {"word": "soap", "hint": "A substance used for washing and cleaning."},
    {"word": "shampoo", "hint": "A liquid used for washing hair."},
    {"word": "towel", "hint": "A piece of cloth used for drying something wet."},
    {"word": "bed", "hint": "A piece of furniture for sleeping on."},
    {"word": "pillow", "hint": "A cushion for supporting the head, especially in bed."},
    {"word": "blanket", "hint": "A large piece of fabric used for warmth."},
    {"word": "carpet", "hint": "A floor covering made from thick woven fabric."},
    {"word": "laptop", "hint": "A portable computer."},
    {"word": "scissors", "hint": "A tool used for cutting paper, cloth, etc."},
    {"word": "ruler", "hint": "A tool used for measuring length."},
    {"word": "glue", "hint": "A substance used for sticking objects or materials together."},
    {"word": "eraser", "hint": "A small piece of rubber used to remove pencil marks."},
    {"word": "sharpener", "hint": "A device used for sharpening pencils."},
    {"word": "crayons", "hint": "Colored wax sticks used for drawing."},
    {"word": "paint", "hint": "A colored substance applied to a surface for protection or decoration."},
    {"word": "brush", "hint": "A tool with bristles used for painting, cleaning, or arranging hair."},
    {"word": "tape", "hint": "A strip of material used for binding or attaching things together."},
    {"word": "folder", "hint": "A cover or holder for keeping loose papers together and organized."},
    {"word": "pencil", "hint": "A writing instrument made of a thin stick of graphite encased in wood."},
    {"word": "marker", "hint": "A pen with a broad tip for marking surfaces."},
    {"word": "chalk", "hint": "A soft white limestone used for writing on blackboards."},
    {"word": "chalkboard", "hint": "A black or green board for writing on with chalk."},
    {"word": "whiteboard", "hint": "A glossy surface for non-permanent markings, typically using dry-erase markers."},
    {"word": "speaker", "hint": "A device that converts electrical signals into sound."},
    {"word": "mouse", "hint": "A hand-held device used to control a cursor on a computer screen."},
    {"word": "keyboard", "hint": "A panel of keys used to operate a computer or typewriter."},
    {"word": "monitor", "hint": "A device that displays visual information from a computer."}
]
